version: '3'

services:
  realtime-stable-diffusion:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root
    # command: python3 app.py
    ports:
      - 7860:7860
    tty:
      true

    working_dir: /root
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]